// Caution: VALUES ARE USED IN SCHEMA
const CONVERSATION_TYPES = {
  SELF: "SELF",
  DIRECT: "DIRECT",
};
Object.freeze(CONVERSATION_TYPES);

const CONVERSATION_MEMBER_ROLES = {
  ADMIN: "ADMIN",
  MEMBER: "MEMBER",
};
Object.freeze(CONVERSATION_MEMBER_ROLES);

module.exports = {
  CONVERSATION_TYPES,
  CONVERSATION_MEMBER_ROLES,
};
