export const ACTION_TYPES = {
  // Profile actions
  FETCH_PROFILE: "FETCH_PROFILE",
  SET_PROFILE: "SET_PROFILE",
  UPDATE_PROFILE: "UPDATE_PROFILE",

  // User actions
  SET_USER: "SET_USER",
  UPDATE_USER: "UPDATE_USER",
  CLEAR_USER: "CLEAR_USER",

  // Conversation actions
  SET_CONVERSATIONS: "SET_CONVERSATIONS",
  UPDATE_CONVERSATIONS: "UPDATE_CONVERSATIONS",
  CLEAR_CONVERSATIONS: "CLEAR_CONVERSATIONS",

  // SOCKET actions

  SET_SOCKET: "SET_SOCKET",
};
